<?php
$title = 'Unit info';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
<tr>
    <th>FullName</th>
    <th>Grade</th>
    <th>&nbsp;</th>
</tr>
<tr>
    <td><?php echo $this->escapeHtml($unit->fullname);?></td>
    <td><?php echo $this->escapeHtml($grade->level), $this->escapeHtml($grade->prefix);?></td>
    <td></td>
</tr>
</table>