<?php
$title = 'Итоговые оценки ученика за месяц';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Ф.И.О: <?php echo $this->escapeHtml($unit->fullname);?></p>
<p>Класс: <?php echo $this->escapeHtml($grade->level), $this->escapeHtml($grade->prefix);?></p>
<p>Месяц: <?php echo $this->escapeHtml(date("F",$month));?></p>
<table class="table">
    <tr>
        <th>Название предмета</th>
        <th>Итоговая оценка</th>
    </tr>
    <?php foreach ($marks as $mark) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($mark['subject_name']);?></td>
            <td><?php echo $this->escapeHtml(number_format( $mark['mark_avg'], 1));?></td>
        </tr>
    <?php endforeach; ?>
</table>