<?php
$title = 'Grade list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin',
        array('action'=>'addgrade'));?>">Add grade</a>
</p>
<table class="table">
<tr>
    <th>Level</th>
    <th>Prefix</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($grades as $grade) : ?>
<tr>
    <td><?php echo $this->escapeHtml($grade->level);?></td>
    <td><?php echo $this->escapeHtml($grade->prefix);?></td>
    <td>
        <a href="<?php echo $this->url('grade',
            array('action'=>'unitlist', 'id' => $grade->id));?>">[Unit List]</a>
        <a href="<?php echo $this->url('grade',
            array('action'=>'subjectlist', 'id' => $grade->id));?>">[Subject List]</a>
    </td>
</tr>
<?php endforeach; ?>
</table>