<?php
$title = 'Список учеников "'.$grade->level.$grade->prefix.'" класса';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
<tr>
    <th>Ф.И.О</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($units as $unit) : ?>
<tr>
    <td><?php echo $this->escapeHtml($unit->fullname);?></td>
    <td>
        <a href="<?php echo $this->url('unit',
            array('id' => $unit->id));?>">Оценки за месяц</a>
    </td>
</tr>
<?php endforeach; ?>
</table>