<?php
$title = 'Add Grade';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin', array('action' => 'addgrade')));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('level'));
echo $this->formRow($form->get('prefix'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
