<?php
$title = 'Edit Mark';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Subject: <?php echo $this->escapeHtml($subject->name); ?></p>
<p>Date: <?php echo $this->escapeHtml($lesson->date); ?></p>
<p>Unit: <?php echo $this->escapeHtml($unit->fullname); ?></p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin', 
        array('action' => 'addmark', 'id1' => $unit->id, 'id2' => $lesson->id)));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('unit_id'));
echo $this->formHidden($form->get('lesson_id'));
echo $this->formRow($form->get('value'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
