<?php
$title = 'Admin panel';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admin',
        array('action'=>'addgrade'));?>">Grade Add</a>
</p>
<p>
    <a href="<?php echo $this->url('admin',
        array('action'=>'addunit'));?>">Unit Add</a>
</p>
<p>
    <a href="<?php echo $this->url('admin',
        array('action'=>'addsuject'));?>">Subject Add</a>
</p>
<p>
    <a href="<?php echo $this->url('admin',
        array('action'=>'addlesson'));?>">Lesson Add</a>
</p>
<p>
    <a href="<?php echo $this->url('admin',
        array('action'=>'addmark'));?>">Mark Add</a>
</p>
