<?php
$title = 'Gradebook on '.$subject->name.' in '.$grade->level.$grade->prefix;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Week:<?php echo $this->escapeHtml(date ('W',$timeS));?></p>
<p><?php echo $this->escapeHtml(date ('d/m',$timeS));?> - 
    <?php echo $this->escapeHtml(date ('d/m',$timeE));?></p>
<a href="<?php echo $this->url('journal',
    array(  'grade_id' => $grade->id,
            'subject_id' => $subject->id,
            'time' => strtotime('-7 days', $timeS),
          )
    );?>">Back</a>
<a href="<?php echo $this->url('journal',
    array(  'grade_id' => $grade->id,
            'subject_id' => $subject->id,
            'time' => strtotime('+7 days', $timeS),
          )
    );?>">Next</a>

<table class="table table-bordered">
    <tr>
        <th>&nbsp;</th>
        <?php foreach ($dates as $date) : ?>
            <th><?php echo $this->escapeHtml(date_format($date, 'd/m'));?></th>
        <?php endforeach; ?>
    </tr>
    <?php foreach ($units as $unit) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($unit['unit']->fullname);?></td>
        <?php foreach ($unit['marks']as $mark) : ?>
            <td><a href="<?php echo $this->url('admin',
            array(  'action' => 'addmark',
                    'id1' => $unit['unit']->id,
                    'id2' => $mark['lesson']->id,
                  )
            );?>"><?php echo $this->escapeHtml($mark['mark']);?></a></td>
        <?php endforeach; ?>
    </tr>
    <?php endforeach; ?>
</table>

