<?php
$title = 'Редактирование оценки';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Предмет: <?php echo $this->escapeHtml($lesson->subject->name); ?></p>
<p>Дата занятия: <?php echo $this->escapeHtml($lesson->date->format("Y-m-d")); ?></p>
<p>Ф.И.О. ученика: <?php echo $this->escapeHtml($unit->fullname); ?></p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/mark', 
        array('action' => 'edit', 
            'unit_id' => $unit->id, 
            'lesson_id' => $lesson->id)));
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('unit_id'));
echo $this->formHidden($form->get('lesson_id'));
echo $this->formRow($form->get('value'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
